name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch: # Allows manual triggering

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/

      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          publish_branch: output
          publish_dir: dist
          commit_message: "Generated Snake Animation"
          keep_history: true
          keep_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
